wordpress:
  build: .
  links:
    - db
  ports:
    - 8189:80
  environment:
      - WORDPRESS_DEBUG=true
      - WORDPRESS_DB_HOST=db
      - WORDPRESS_DB_USER=root
      - WORDPRESS_DB_PASSWORD=root
      - WORDPRESS_DB_PORT=3366
db:
  image: mariadb
  ports:
      - "3366:3306"

  environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=azpay
      - MYSQL_PASSWORD=azpay123
      - MYSQL_DATABASE=db
